server.port: 9090
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/JobMarketplace
    username: postgres
    password: XrosBBZBL07
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/job-marketplace
keycloak:
  server-url: http://localhost:8080
  realm: job-marketplace
  admin-client-id: job-marketplace-admin
  admin-client-secret: rWkZo26lRx56qKcLX1zRXmQYIZVgoew4
  login-client-id: job-marketplace-api
  login-client-secret: 813HgakjUgvoe2buWYuznFIsEP7WlxMC
app:
  name: jobmarketplace