server.port: 9090
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/JobMarketplace
    username: HIER_USERNAME_EINFÜGEN
    password: HIER_PASSWORT_EINFÜGEN
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/job-marketplace
keycloak:
  server-url: http://localhost:8080
  realm: job-marketplace
  admin-client-id: job-marketplace-admin
  admin-client-secret: HIER_SECRET_EINFÜGEN
  login-client-id: job-marketplace-api
  login-client-secret: HIER_SECRET_EINFÜGEN
logging:
  level:
    org.springframework.security: DEBUG